name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Tests
        run: go test -cover ./...

      - name: Force Failure
        run: (exit 0)
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: gosec
        uses: securego/gosec@master
        with:
          args: ./... 

  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Style
        run: test -z $(go fmt ./...) && echo $?
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
